$axure.loadCurrentPage({
  "url":"stuentlist.html",
  "generationDate":new Date(1527758794597.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c3e78a91fce54f82b45b2e74415e7edd",
    "type":"Axure:Page",
    "name":"stuentList",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d262b8770074a72818839eae1a777dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":580,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f7eb92aa4b4418795223e3df5f9d126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":580,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stuentlist/u0.png"}},
{
          "id":"59c01c4409734cde8c522d10c6826727",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":120},
            "size":{
              "width":540,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b3856737d34c26b6e071b51c6aa49e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f84afcad91ee462db5c32439cd24dd74",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u3.png"}},
{
              "id":"8756f5b20d95405c98b1bcadea74445c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c5cf6681b82c4ac0b302a8c0e499c0af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u3.png"}},
{
              "id":"34a164d409334712bd969ef94ada630e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":135,
                  "height":150}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"748cbd1ce51b4e64b493330b8e5bac1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":150}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u19.png"}},
{
              "id":"4975a7f1d9e74f96b0f75f5f62ad8928",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":0},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77e9927239ed4082a4da4e3ad5793ff8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u3.png"}},
{
              "id":"fac99a97aa13459e88511a561d50bbcd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b06757ba5fd49ceb72fe2f80c85074e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u3.png"}},
{
              "id":"47ef726146624205b7b69ce7be26ad9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":60},
                "size":{
                  "width":135,
                  "height":150}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed3e53f2c3de4f9ab37b002364bf77e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":150}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u19.png"}},
{
              "id":"ba0d4b3f0f8c4b2389418ea08e6cecf9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":0},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7908abd048b04139b4d2a60b6bf94b45",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":270,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u3.png"}},
{
              "id":"1ee8b1bc2a4d4818b50c891cf483d795",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69b8f33f53ac401c9eb0e6c1df759ffe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":270,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u3.png"}},
{
              "id":"4320ed550da346cf9273683f6a04f5f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":60},
                "size":{
                  "width":135,
                  "height":150}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89dea48842514756933280fe98ddf406",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":270,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":150}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u19.png"}},
{
              "id":"cfa8d0c94878452ab7024b9e6c4ba775",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":405,
                  "y":0},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6c21bfcccb3491384d0e43e960c4f5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":405,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u9.png"}},
{
              "id":"f8fc4e59a0654b958977a6ca43c4fcd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":405,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2272ab9111114de6a49ea87d724a4ff2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":405,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u9.png"}},
{
              "id":"00ceaeb375a34fa782a0e09b28515300",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":405,
                  "y":60},
                "size":{
                  "width":135,
                  "height":150}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cc8983710e94e0eb03f05208efe871d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":405,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":150}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stuentlist/u25.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "4d262b8770074a72818839eae1a777dc":{
      "scriptId":"u0"},
    "3f7eb92aa4b4418795223e3df5f9d126":{
      "scriptId":"u1"},
    "59c01c4409734cde8c522d10c6826727":{
      "scriptId":"u2"},
    "71b3856737d34c26b6e071b51c6aa49e":{
      "scriptId":"u3"},
    "f84afcad91ee462db5c32439cd24dd74":{
      "scriptId":"u4"},
    "4975a7f1d9e74f96b0f75f5f62ad8928":{
      "scriptId":"u5"},
    "77e9927239ed4082a4da4e3ad5793ff8":{
      "scriptId":"u6"},
    "ba0d4b3f0f8c4b2389418ea08e6cecf9":{
      "scriptId":"u7"},
    "7908abd048b04139b4d2a60b6bf94b45":{
      "scriptId":"u8"},
    "cfa8d0c94878452ab7024b9e6c4ba775":{
      "scriptId":"u9"},
    "b6c21bfcccb3491384d0e43e960c4f5b":{
      "scriptId":"u10"},
    "8756f5b20d95405c98b1bcadea74445c":{
      "scriptId":"u11"},
    "c5cf6681b82c4ac0b302a8c0e499c0af":{
      "scriptId":"u12"},
    "fac99a97aa13459e88511a561d50bbcd":{
      "scriptId":"u13"},
    "1b06757ba5fd49ceb72fe2f80c85074e":{
      "scriptId":"u14"},
    "1ee8b1bc2a4d4818b50c891cf483d795":{
      "scriptId":"u15"},
    "69b8f33f53ac401c9eb0e6c1df759ffe":{
      "scriptId":"u16"},
    "f8fc4e59a0654b958977a6ca43c4fcd5":{
      "scriptId":"u17"},
    "2272ab9111114de6a49ea87d724a4ff2":{
      "scriptId":"u18"},
    "34a164d409334712bd969ef94ada630e":{
      "scriptId":"u19"},
    "748cbd1ce51b4e64b493330b8e5bac1b":{
      "scriptId":"u20"},
    "47ef726146624205b7b69ce7be26ad9f":{
      "scriptId":"u21"},
    "ed3e53f2c3de4f9ab37b002364bf77e5":{
      "scriptId":"u22"},
    "4320ed550da346cf9273683f6a04f5f8":{
      "scriptId":"u23"},
    "89dea48842514756933280fe98ddf406":{
      "scriptId":"u24"},
    "00ceaeb375a34fa782a0e09b28515300":{
      "scriptId":"u25"},
    "7cc8983710e94e0eb03f05208efe871d":{
      "scriptId":"u26"}}});