$axure.loadCurrentPage({
  "url":"stugrademanage.html",
  "generationDate":new Date(1527758795123.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"492a38bbffe642f58e81768f3fd552a6",
    "type":"Axure:Page",
    "name":"stuGradeManage",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e01179c2e782443aad979b916409b311",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":910,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295f18745add4697a7b03c30f08c29ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":910,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/showgrade/u0.png"}},
{
          "id":"53b50c27ffa34890ba726a7d08be1268",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":30},
            "size":{
              "width":850,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d68c9f3777df40c4a88b87841d7e52ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"301f8e7818bd4f91b45a25a23ab98eee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u3.png"}},
{
              "id":"c0d44a48db904237b6bd8f315a72ba78",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94fe5771d9fc496bad26807fca0a3555",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u3.png"}},
{
              "id":"b053b049d67f487e97c09448cd4aa966",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":103,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68f3e71fd25d4536a62d98510e869cdb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":103,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u51.png"}},
{
              "id":"ba1d2fb340e1418792633d252e5b5a10",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":55,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4a75dcd7c9d4e209328bcdfca460094",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":0},
                    "size":{
                      "width":55,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u5.png"}},
{
              "id":"a3e8d19918c344de9609d84b1fe6bac6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":30},
                "size":{
                  "width":55,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3ade4141e434f158d802451e24de2d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":30},
                    "size":{
                      "width":55,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u5.png"}},
{
              "id":"2ce7fca1a3d54f0a9d110ac1b9950ea6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":60},
                "size":{
                  "width":55,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6fd7d4a85985408ebadf0d911a99197d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":60},
                    "size":{
                      "width":55,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u53.png"}},
{
              "id":"e887213d70fc4e6a870413a9a36bd89d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":0},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50fb3ac7f160485fa54745eaa7c6533a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u7.png"}},
{
              "id":"388ddb4e5de94cadb36bddbe6ab64e64",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":30},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b987f7d9c6e4aaa87c6a0238699428c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":30},
                    "size":{
                      "width":66,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u7.png"}},
{
              "id":"145e3e8f835e40aa80bb990b28e3a71f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":60},
                "size":{
                  "width":66,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6ff9ce069974051b2ffc1d0539e9e7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":60},
                    "size":{
                      "width":66,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u55.png"}},
{
              "id":"1a78d3d212ec4295a6c10deb11a06608",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":0},
                "size":{
                  "width":82,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5075aa8112c4dcebae4c6524f108b47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u9.png"}},
{
              "id":"c7317adb83314af8b7c8fbb2e33fa401",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":30},
                "size":{
                  "width":82,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"642507e16586413cb9ac2e90f3f3bc6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":30},
                    "size":{
                      "width":82,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u9.png"}},
{
              "id":"175a152078f9497eb830bd7af1528b0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":60},
                "size":{
                  "width":82,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e2b599ac43e46488b3da08639359d0b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":60},
                    "size":{
                      "width":82,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u57.png"}},
{
              "id":"cdb89f543f9d46a1b8e4883c0a5c5282",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":0},
                "size":{
                  "width":63,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69aed9f5fdb1432dac745bf7791f7bfd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":0},
                    "size":{
                      "width":63,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u11.png"}},
{
              "id":"0cbb7bdb482e4c7593bb00ba0b375d8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":30},
                "size":{
                  "width":63,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7aaf8206b5d49d5a4c73d246caf39ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":30},
                    "size":{
                      "width":63,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u11.png"}},
{
              "id":"350aefcff09c42529330f257ef540a53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":60},
                "size":{
                  "width":63,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d086247773904873a6f610fba220ab94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":60},
                    "size":{
                      "width":63,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u59.png"}},
{
              "id":"686275474a2b4026b662a7258f4634fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":369,
                  "y":0},
                "size":{
                  "width":69,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed6704063ea2456fab593f29cfcd6d33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":369,
                      "y":0},
                    "size":{
                      "width":69,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u7.png"}},
{
              "id":"c0b0b28c51f743538df5a4e19fa67a98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":369,
                  "y":30},
                "size":{
                  "width":69,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9f9513243a448b49da1155dc52d4cad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":369,
                      "y":30},
                    "size":{
                      "width":69,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u7.png"}},
{
              "id":"00580b79cc71462faeb3124917b79d50",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":369,
                  "y":60},
                "size":{
                  "width":69,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45dabb71cba040e0b471c4a74bb06fa2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":369,
                      "y":60},
                    "size":{
                      "width":69,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u51.png"}},
{
              "id":"7c0a2059c3e34bb3ace54a17d685f19c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":438,
                  "y":0},
                "size":{
                  "width":73,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49eebaaae66941bca2015ce14c2e1b4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":438,
                      "y":0},
                    "size":{
                      "width":73,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u15.png"}},
{
              "id":"616f8ec3c28b4e94ac94406f5ee0ecde",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":438,
                  "y":30},
                "size":{
                  "width":73,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5b8526b3bdb412d8a75cb47f67bf1ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":438,
                      "y":30},
                    "size":{
                      "width":73,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u15.png"}},
{
              "id":"2a7da6b67cf84873bb13a1102a6dee52",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":438,
                  "y":60},
                "size":{
                  "width":73,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d9660fbddd94e07b8173e6b0341e0ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":438,
                      "y":60},
                    "size":{
                      "width":73,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u63.png"}},
{
              "id":"a70b0e98fba646179babb63d4ca25c93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":511,
                  "y":0},
                "size":{
                  "width":67,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f8ecac0c0ea4143b3034a6b5b101ab1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":511,
                      "y":0},
                    "size":{
                      "width":67,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u17.png"}},
{
              "id":"0d8257d0d66b411db337094222508d12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":511,
                  "y":30},
                "size":{
                  "width":67,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec1ea0d90de44c098fb8afeef0a79edf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":511,
                      "y":30},
                    "size":{
                      "width":67,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u17.png"}},
{
              "id":"1614fb8d447b46fdba4c40111fc3fdb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":511,
                  "y":60},
                "size":{
                  "width":67,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"226c5c6cf058436297f6b6b6b1a5300e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":511,
                      "y":60},
                    "size":{
                      "width":67,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u65.png"}},
{
              "id":"d812d128097b44e895a60c207c50b79b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":578,
                  "y":0},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"103561143886447daccef90ab4308fae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":578,
                      "y":0},
                    "size":{
                      "width":64,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u19.png"}},
{
              "id":"f8d04c99e40549bc80e90bdfb2eb0849",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":578,
                  "y":30},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"614a42db5c054bff9a34e136cffdcbf5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":578,
                      "y":30},
                    "size":{
                      "width":64,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u19.png"}},
{
              "id":"9f35fe743d104a47804b923508b82fd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":578,
                  "y":60},
                "size":{
                  "width":64,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bb99715d1c247618437015278a69a15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":578,
                      "y":60},
                    "size":{
                      "width":64,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u67.png"}},
{
              "id":"ac4d7a70b9eb40f3b5f41994bd697e02",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":642,
                  "y":0},
                "size":{
                  "width":61,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a8bd1cf8a9e424591180ec7eddce882",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":642,
                      "y":0},
                    "size":{
                      "width":61,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u21.png"}},
{
              "id":"68a60afc162e4de3b930b0ae9125cb47",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":642,
                  "y":30},
                "size":{
                  "width":61,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad07ca6cac0e4e64b8315e073df69fac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":642,
                      "y":30},
                    "size":{
                      "width":61,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u21.png"}},
{
              "id":"309ff0d960214800bddac548fbfa5f96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":642,
                  "y":60},
                "size":{
                  "width":61,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"271a18416f8b40e8ba5a7d9474458bd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":642,
                      "y":60},
                    "size":{
                      "width":61,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u69.png"}},
{
              "id":"bb1fa532f7e2429ca52478590713ec4e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":703,
                  "y":0},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e746c48548e6402e87176089170c04b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":703,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u11.png"}},
{
              "id":"0db6c02a4c824efb9da9c2c1e93fd9c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":703,
                  "y":30},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94b89c3c84b6483da754289bd266fe44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":703,
                      "y":30},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u11.png"}},
{
              "id":"dbf3a38a586f4513929ed0d83bcfc4eb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":703,
                  "y":60},
                "size":{
                  "width":75,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c86c432be0f40f48e579900642f0bee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":703,
                      "y":60},
                    "size":{
                      "width":75,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u55.png"}},
{
              "id":"c7661ef31cf540809f1f77d971c3d91e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":778,
                  "y":0},
                "size":{
                  "width":72,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"829f583b019a4dadbf32d97295ec87f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":778,
                      "y":0},
                    "size":{
                      "width":72,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u25.png"}},
{
              "id":"f1a957f05d3948a0b5dc67a1981b1f6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":778,
                  "y":30},
                "size":{
                  "width":72,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91c3d9b301f54a7bb49836dc28acf72e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":778,
                      "y":30},
                    "size":{
                      "width":72,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u25.png"}},
{
              "id":"8b4d73904a81445baaa1e9eb8d07a156",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":778,
                  "y":60},
                "size":{
                  "width":72,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6a788ffb19640a7b9e0e5bc19e72872",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":778,
                      "y":60},
                    "size":{
                      "width":72,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u73.png"}}]},
{
          "id":"80c70d2c8c6a4b1e8e31730692ca7f28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":100},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1c01a628e6457f8b86ece0b81ce4a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":100},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee66c5c3d67d45b99688f071c989f287",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":841,
              "y":64},
            "size":{
              "width":49,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c145deffe164d0e871405ea816b7e61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":841,
                  "y":64},
                "size":{
                  "width":49,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stugrademanage/u77.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e01179c2e782443aad979b916409b311":{
      "scriptId":"u0"},
    "295f18745add4697a7b03c30f08c29ca":{
      "scriptId":"u1"},
    "53b50c27ffa34890ba726a7d08be1268":{
      "scriptId":"u2"},
    "d68c9f3777df40c4a88b87841d7e52ac":{
      "scriptId":"u3"},
    "301f8e7818bd4f91b45a25a23ab98eee":{
      "scriptId":"u4"},
    "ba1d2fb340e1418792633d252e5b5a10":{
      "scriptId":"u5"},
    "f4a75dcd7c9d4e209328bcdfca460094":{
      "scriptId":"u6"},
    "e887213d70fc4e6a870413a9a36bd89d":{
      "scriptId":"u7"},
    "50fb3ac7f160485fa54745eaa7c6533a":{
      "scriptId":"u8"},
    "1a78d3d212ec4295a6c10deb11a06608":{
      "scriptId":"u9"},
    "d5075aa8112c4dcebae4c6524f108b47":{
      "scriptId":"u10"},
    "cdb89f543f9d46a1b8e4883c0a5c5282":{
      "scriptId":"u11"},
    "69aed9f5fdb1432dac745bf7791f7bfd":{
      "scriptId":"u12"},
    "686275474a2b4026b662a7258f4634fa":{
      "scriptId":"u13"},
    "ed6704063ea2456fab593f29cfcd6d33":{
      "scriptId":"u14"},
    "7c0a2059c3e34bb3ace54a17d685f19c":{
      "scriptId":"u15"},
    "49eebaaae66941bca2015ce14c2e1b4b":{
      "scriptId":"u16"},
    "a70b0e98fba646179babb63d4ca25c93":{
      "scriptId":"u17"},
    "1f8ecac0c0ea4143b3034a6b5b101ab1":{
      "scriptId":"u18"},
    "d812d128097b44e895a60c207c50b79b":{
      "scriptId":"u19"},
    "103561143886447daccef90ab4308fae":{
      "scriptId":"u20"},
    "ac4d7a70b9eb40f3b5f41994bd697e02":{
      "scriptId":"u21"},
    "3a8bd1cf8a9e424591180ec7eddce882":{
      "scriptId":"u22"},
    "bb1fa532f7e2429ca52478590713ec4e":{
      "scriptId":"u23"},
    "e746c48548e6402e87176089170c04b9":{
      "scriptId":"u24"},
    "c7661ef31cf540809f1f77d971c3d91e":{
      "scriptId":"u25"},
    "829f583b019a4dadbf32d97295ec87f7":{
      "scriptId":"u26"},
    "c0d44a48db904237b6bd8f315a72ba78":{
      "scriptId":"u27"},
    "94fe5771d9fc496bad26807fca0a3555":{
      "scriptId":"u28"},
    "a3e8d19918c344de9609d84b1fe6bac6":{
      "scriptId":"u29"},
    "c3ade4141e434f158d802451e24de2d1":{
      "scriptId":"u30"},
    "388ddb4e5de94cadb36bddbe6ab64e64":{
      "scriptId":"u31"},
    "6b987f7d9c6e4aaa87c6a0238699428c":{
      "scriptId":"u32"},
    "c7317adb83314af8b7c8fbb2e33fa401":{
      "scriptId":"u33"},
    "642507e16586413cb9ac2e90f3f3bc6b":{
      "scriptId":"u34"},
    "0cbb7bdb482e4c7593bb00ba0b375d8a":{
      "scriptId":"u35"},
    "f7aaf8206b5d49d5a4c73d246caf39ba":{
      "scriptId":"u36"},
    "c0b0b28c51f743538df5a4e19fa67a98":{
      "scriptId":"u37"},
    "f9f9513243a448b49da1155dc52d4cad":{
      "scriptId":"u38"},
    "616f8ec3c28b4e94ac94406f5ee0ecde":{
      "scriptId":"u39"},
    "a5b8526b3bdb412d8a75cb47f67bf1ef":{
      "scriptId":"u40"},
    "0d8257d0d66b411db337094222508d12":{
      "scriptId":"u41"},
    "ec1ea0d90de44c098fb8afeef0a79edf":{
      "scriptId":"u42"},
    "f8d04c99e40549bc80e90bdfb2eb0849":{
      "scriptId":"u43"},
    "614a42db5c054bff9a34e136cffdcbf5":{
      "scriptId":"u44"},
    "68a60afc162e4de3b930b0ae9125cb47":{
      "scriptId":"u45"},
    "ad07ca6cac0e4e64b8315e073df69fac":{
      "scriptId":"u46"},
    "0db6c02a4c824efb9da9c2c1e93fd9c7":{
      "scriptId":"u47"},
    "94b89c3c84b6483da754289bd266fe44":{
      "scriptId":"u48"},
    "f1a957f05d3948a0b5dc67a1981b1f6b":{
      "scriptId":"u49"},
    "91c3d9b301f54a7bb49836dc28acf72e":{
      "scriptId":"u50"},
    "b053b049d67f487e97c09448cd4aa966":{
      "scriptId":"u51"},
    "68f3e71fd25d4536a62d98510e869cdb":{
      "scriptId":"u52"},
    "2ce7fca1a3d54f0a9d110ac1b9950ea6":{
      "scriptId":"u53"},
    "6fd7d4a85985408ebadf0d911a99197d":{
      "scriptId":"u54"},
    "145e3e8f835e40aa80bb990b28e3a71f":{
      "scriptId":"u55"},
    "f6ff9ce069974051b2ffc1d0539e9e7f":{
      "scriptId":"u56"},
    "175a152078f9497eb830bd7af1528b0e":{
      "scriptId":"u57"},
    "8e2b599ac43e46488b3da08639359d0b":{
      "scriptId":"u58"},
    "350aefcff09c42529330f257ef540a53":{
      "scriptId":"u59"},
    "d086247773904873a6f610fba220ab94":{
      "scriptId":"u60"},
    "00580b79cc71462faeb3124917b79d50":{
      "scriptId":"u61"},
    "45dabb71cba040e0b471c4a74bb06fa2":{
      "scriptId":"u62"},
    "2a7da6b67cf84873bb13a1102a6dee52":{
      "scriptId":"u63"},
    "2d9660fbddd94e07b8173e6b0341e0ca":{
      "scriptId":"u64"},
    "1614fb8d447b46fdba4c40111fc3fdb7":{
      "scriptId":"u65"},
    "226c5c6cf058436297f6b6b6b1a5300e":{
      "scriptId":"u66"},
    "9f35fe743d104a47804b923508b82fd5":{
      "scriptId":"u67"},
    "5bb99715d1c247618437015278a69a15":{
      "scriptId":"u68"},
    "309ff0d960214800bddac548fbfa5f96":{
      "scriptId":"u69"},
    "271a18416f8b40e8ba5a7d9474458bd1":{
      "scriptId":"u70"},
    "dbf3a38a586f4513929ed0d83bcfc4eb":{
      "scriptId":"u71"},
    "7c86c432be0f40f48e579900642f0bee":{
      "scriptId":"u72"},
    "8b4d73904a81445baaa1e9eb8d07a156":{
      "scriptId":"u73"},
    "c6a788ffb19640a7b9e0e5bc19e72872":{
      "scriptId":"u74"},
    "80c70d2c8c6a4b1e8e31730692ca7f28":{
      "scriptId":"u75"},
    "cb1c01a628e6457f8b86ece0b81ce4a5":{
      "scriptId":"u76"},
    "ee66c5c3d67d45b99688f071c989f287":{
      "scriptId":"u77"},
    "3c145deffe164d0e871405ea816b7e61":{
      "scriptId":"u78"}}});