$axure.loadCurrentPage({
  "url":"logout.html",
  "generationDate":new Date(1527843569579.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"179a41d0ecc5494da890a97f7a74948c",
    "type":"Axure:Page",
    "name":"logout",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"848fa57ce760445592ed056f0fa4c52b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":90},
            "size":{
              "width":450,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da828427cc2447a289065db027be11e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":90},
                "size":{
                  "width":450,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logout/u0.png"}},
{
          "id":"5e30f9778ca54213ae9c7f3565f50787",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":97},
            "size":{
              "width":430,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69997f1962c741f9b2fc817703a077e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":97},
                "size":{
                  "width":430,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logout/u2.png"}},
{
          "id":"c844ca8dcfb748369e361dcb86f8aaed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":30},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afef742baf2472495e745b50625beb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":298,
                  "y":30},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"604568a33d6e4f2cad1b4f058215f630",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":101},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c5ab069431448cdafb56da7791f4ff8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":101},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logout/u6.png"}},
{
          "id":"3670bae995464a5cb6017bfe9e65a35b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":140},
            "size":{
              "width":430,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f79a900dae24a55a08e549da6f9e923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":140},
                "size":{
                  "width":430,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logout/u8.png"}},
{
          "id":"ee041e90fce24f8dbcb90c290a636b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":104},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a909d3da9849e1afd1b447fec0cd37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":104},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e30e851eef544874b8592e082d188d65",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8eb732dfbf645eda12b420c7f1dd6e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":110}},
              "adaptiveStyles":{
}}]},
{
          "id":"1809ca45d8a34a1db9db4ea985801f0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":184},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b92c8702a324d44b9647037ffd5add4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":184},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "848fa57ce760445592ed056f0fa4c52b":{
      "scriptId":"u0"},
    "da828427cc2447a289065db027be11e3":{
      "scriptId":"u1"},
    "5e30f9778ca54213ae9c7f3565f50787":{
      "scriptId":"u2"},
    "69997f1962c741f9b2fc817703a077e7":{
      "scriptId":"u3"},
    "c844ca8dcfb748369e361dcb86f8aaed":{
      "scriptId":"u4"},
    "7afef742baf2472495e745b50625beb4":{
      "scriptId":"u5"},
    "604568a33d6e4f2cad1b4f058215f630":{
      "scriptId":"u6"},
    "6c5ab069431448cdafb56da7791f4ff8":{
      "scriptId":"u7"},
    "3670bae995464a5cb6017bfe9e65a35b":{
      "scriptId":"u8"},
    "8f79a900dae24a55a08e549da6f9e923":{
      "scriptId":"u9"},
    "ee041e90fce24f8dbcb90c290a636b2c":{
      "scriptId":"u10"},
    "94a909d3da9849e1afd1b447fec0cd37":{
      "scriptId":"u11"},
    "e30e851eef544874b8592e082d188d65":{
      "scriptId":"u12"},
    "b8eb732dfbf645eda12b420c7f1dd6e1":{
      "scriptId":"u13"},
    "1809ca45d8a34a1db9db4ea985801f0d":{
      "scriptId":"u14"},
    "4b92c8702a324d44b9647037ffd5add4":{
      "scriptId":"u15"}}});