$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1527758794429.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ad9c72f29c904d85b313dc400a507935",
    "type":"Axure:Page",
    "name":"login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b9a98ba75f4248f9a0a32d04a496248b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":100},
            "size":{
              "width":400,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b55b539d727f4f45a1a0c2c751f075ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":100},
                "size":{
                  "width":400,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"ca501a2269b64b86a732c8e9a6dd81c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":130},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1380905f2f7e440aa88ee729c44827f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":130},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"619e4d79057e4e51a6f33a94045ca531",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":190},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7324dbe3fdf4190a7f73144ba12557d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":190},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"a9350554b0c548deac6e93872299ccfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":137},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf3117aa0d1c42b49bbceafe1da3d5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":137},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d499870233b947ecac9e0f504d40eb7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":197},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d965aa5932334c7d96ce445789b4647a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":197},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81b94c19de984890bdbbab37f766ffec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":270},
            "size":{
              "width":270,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e38417043c4a01bdbb2fe3553e8636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":270},
                "size":{
                  "width":270,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b9a98ba75f4248f9a0a32d04a496248b":{
      "scriptId":"u0"},
    "b55b539d727f4f45a1a0c2c751f075ce":{
      "scriptId":"u1"},
    "ca501a2269b64b86a732c8e9a6dd81c2":{
      "scriptId":"u2"},
    "1380905f2f7e440aa88ee729c44827f8":{
      "scriptId":"u3"},
    "619e4d79057e4e51a6f33a94045ca531":{
      "scriptId":"u4"},
    "a7324dbe3fdf4190a7f73144ba12557d":{
      "scriptId":"u5"},
    "a9350554b0c548deac6e93872299ccfc":{
      "scriptId":"u6"},
    "cf3117aa0d1c42b49bbceafe1da3d5a4":{
      "scriptId":"u7"},
    "d499870233b947ecac9e0f504d40eb7c":{
      "scriptId":"u8"},
    "d965aa5932334c7d96ce445789b4647a":{
      "scriptId":"u9"},
    "81b94c19de984890bdbbab37f766ffec":{
      "scriptId":"u10"},
    "92e38417043c4a01bdbb2fe3553e8636":{
      "scriptId":"u11"}}});