$axure.loadCurrentPage({
  "url":"taskpublish.html",
  "generationDate":new Date(1527758795322.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"28950cb53c5c48b9be147d0ca2cbe5ba",
    "type":"Axure:Page",
    "name":"taskPublish",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e9fe51cdb3df4ca5b117bf407cd4b16f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":810,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91378180560418b98d647166abc0f06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":810,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/taskpublish/u0.png"}},
{
          "id":"4b7400fa7077407aa09876d464861499",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":30},
            "size":{
              "width":764,
              "height":459}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9ad6a0eeae4a17829bc8fa33edcded",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":103,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"964c1b54dfd8456ea4c808b11d761741",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":103,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u3.png"}},
{
              "id":"8e9497bd4a4f44b79845db08cc35c6f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"493ec93b38504579af59ae7d4504ccbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u3.png"}},
{
              "id":"15d3f7deafe04731bf9b0ea1a06f5f2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":103,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c966810aeb7d4cb2ace87469980954b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":69},
                    "size":{
                      "width":103,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u51.png"}},
{
              "id":"44fa23eb6fb5449ab89612864569be7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":71,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d319edd85ef24fcdb4a554bee7b24fc7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u5.png"}},
{
              "id":"f16607156483482383dd923c968ff5cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":39},
                "size":{
                  "width":71,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf2f58ddf8bd4949919ac7c2a33c11dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":39},
                    "size":{
                      "width":71,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u21.png"}},
{
              "id":"58a3aeb92cd44813b6788929a429fd21",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":69},
                "size":{
                  "width":71,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c219f5cd19a84563b52112867025a2a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":69},
                    "size":{
                      "width":71,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u37.png"}},
{
              "id":"6ba323ac99e04da887c3c3c8c1011a0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":174,
                  "y":0},
                "size":{
                  "width":50,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f8d0dad5d0b40179283ef733c716854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":174,
                      "y":0},
                    "size":{
                      "width":50,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u7.png"}},
{
              "id":"45884f5d84594ffaa346eed3f82cecc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":174,
                  "y":39},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21ee639586074ec3a7ca6b3294b8caac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":174,
                      "y":39},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u23.png"}},
{
              "id":"500f102c246e4f7f99a351f6a34e405b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":174,
                  "y":69},
                "size":{
                  "width":50,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43cbf13cf0c14997ab1d5f5aa1d21c5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":174,
                      "y":69},
                    "size":{
                      "width":50,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u39.png"}},
{
              "id":"15e63fd45f9247b4b730165804cff078",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":0},
                "size":{
                  "width":82,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bb90dabafc4429cac5438e2e3897a83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u9.png"}},
{
              "id":"23690951724f41a18de9366b6f0becb1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":39},
                "size":{
                  "width":82,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fde4eaebb1d846a9969ec565fd846d32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":39},
                    "size":{
                      "width":82,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u9.png"}},
{
              "id":"49fb91a94b8a4d728fe20b8c49bf7bd9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":69},
                "size":{
                  "width":82,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ddbbe50cb3a743459a9b8892949c6b5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":69},
                    "size":{
                      "width":82,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u57.png"}},
{
              "id":"7c0d346a8a644511ab1dde8d225a267e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":0},
                "size":{
                  "width":61,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c05e33bf352f4dc8841a8dbe6d74c9ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":0},
                    "size":{
                      "width":61,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u11.png"}},
{
              "id":"f44ba93545b2403993ba7d4b4ac5e1b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":39},
                "size":{
                  "width":61,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0474518804074d1a919e5cba23aa4475",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":39},
                    "size":{
                      "width":61,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u21.png"}},
{
              "id":"0e1362c342ec4d37ba07e5eaae76937c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":69},
                "size":{
                  "width":61,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed4fff34955d41e7a37d28f1e57e329e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":69},
                    "size":{
                      "width":61,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u69.png"}},
{
              "id":"5588762480b541c0ab9b48d957a47c06",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":367,
                  "y":0},
                "size":{
                  "width":75,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"859eaa2716814226a3b1aa83adbdf9cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":367,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u13.png"}},
{
              "id":"6bd302f763c94c74b25350d54d435d2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":367,
                  "y":39},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30251ec8d3d9407ba95042cbbe090d87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":367,
                      "y":39},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u11.png"}},
{
              "id":"bbc192c3d31348789677ceffabaf0553",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":75,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc1300964f864514b202a760116ee7ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":367,
                      "y":69},
                    "size":{
                      "width":75,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/showgrade/u55.png"}},
{
              "id":"c8afcba63c0940a294ce14aab52a350f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":0},
                "size":{
                  "width":232,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"65318c52cf0f4c91a36f9dd7334f806a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":0},
                    "size":{
                      "width":232,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u15.png"}},
{
              "id":"af85ecf7eb7e4202972777fe0a213a82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":39},
                "size":{
                  "width":232,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7273ff5ceee046bca6821e29645b44b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":39},
                    "size":{
                      "width":232,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u31.png"}},
{
              "id":"451d90c7945840a7873cd4cf80d35da1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":442,
                  "y":69},
                "size":{
                  "width":232,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cc99b1136564538a3986e9a5deffc51",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":442,
                      "y":69},
                    "size":{
                      "width":232,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u47.png"}},
{
              "id":"743ad1b4409a452f98f51f66ce1550c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":674,
                  "y":0},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"020b7d5a693047c4bf84b60728edda05",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":674,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u17.png"}},
{
              "id":"8fca95cbfacb471381c7dad2141766fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":674,
                  "y":39},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9629f39492014dc69589ec88d93c90ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":674,
                      "y":39},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u33.png"}},
{
              "id":"9779854c81c141e0a77dcfdf31feac65",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":674,
                  "y":69},
                "size":{
                  "width":90,
                  "height":390}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c28353fe38d4b51b1786a280110e250",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":674,
                      "y":69},
                    "size":{
                      "width":90,
                      "height":390}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u49.png"}}]},
{
          "id":"7032b60122754ceea43aeea1ef6efbd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":114},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ca3ba9e45c4b768c314f1a740dd3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":114},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e9fe51cdb3df4ca5b117bf407cd4b16f":{
      "scriptId":"u0"},
    "a91378180560418b98d647166abc0f06":{
      "scriptId":"u1"},
    "4b7400fa7077407aa09876d464861499":{
      "scriptId":"u2"},
    "eb9ad6a0eeae4a17829bc8fa33edcded":{
      "scriptId":"u3"},
    "964c1b54dfd8456ea4c808b11d761741":{
      "scriptId":"u4"},
    "44fa23eb6fb5449ab89612864569be7c":{
      "scriptId":"u5"},
    "d319edd85ef24fcdb4a554bee7b24fc7":{
      "scriptId":"u6"},
    "6ba323ac99e04da887c3c3c8c1011a0d":{
      "scriptId":"u7"},
    "9f8d0dad5d0b40179283ef733c716854":{
      "scriptId":"u8"},
    "15e63fd45f9247b4b730165804cff078":{
      "scriptId":"u9"},
    "8bb90dabafc4429cac5438e2e3897a83":{
      "scriptId":"u10"},
    "7c0d346a8a644511ab1dde8d225a267e":{
      "scriptId":"u11"},
    "c05e33bf352f4dc8841a8dbe6d74c9ae":{
      "scriptId":"u12"},
    "5588762480b541c0ab9b48d957a47c06":{
      "scriptId":"u13"},
    "859eaa2716814226a3b1aa83adbdf9cc":{
      "scriptId":"u14"},
    "c8afcba63c0940a294ce14aab52a350f":{
      "scriptId":"u15"},
    "65318c52cf0f4c91a36f9dd7334f806a":{
      "scriptId":"u16"},
    "743ad1b4409a452f98f51f66ce1550c7":{
      "scriptId":"u17"},
    "020b7d5a693047c4bf84b60728edda05":{
      "scriptId":"u18"},
    "8e9497bd4a4f44b79845db08cc35c6f6":{
      "scriptId":"u19"},
    "493ec93b38504579af59ae7d4504ccbb":{
      "scriptId":"u20"},
    "f16607156483482383dd923c968ff5cf":{
      "scriptId":"u21"},
    "cf2f58ddf8bd4949919ac7c2a33c11dd":{
      "scriptId":"u22"},
    "45884f5d84594ffaa346eed3f82cecc7":{
      "scriptId":"u23"},
    "21ee639586074ec3a7ca6b3294b8caac":{
      "scriptId":"u24"},
    "23690951724f41a18de9366b6f0becb1":{
      "scriptId":"u25"},
    "fde4eaebb1d846a9969ec565fd846d32":{
      "scriptId":"u26"},
    "f44ba93545b2403993ba7d4b4ac5e1b7":{
      "scriptId":"u27"},
    "0474518804074d1a919e5cba23aa4475":{
      "scriptId":"u28"},
    "6bd302f763c94c74b25350d54d435d2c":{
      "scriptId":"u29"},
    "30251ec8d3d9407ba95042cbbe090d87":{
      "scriptId":"u30"},
    "af85ecf7eb7e4202972777fe0a213a82":{
      "scriptId":"u31"},
    "7273ff5ceee046bca6821e29645b44b7":{
      "scriptId":"u32"},
    "8fca95cbfacb471381c7dad2141766fe":{
      "scriptId":"u33"},
    "9629f39492014dc69589ec88d93c90ea":{
      "scriptId":"u34"},
    "15d3f7deafe04731bf9b0ea1a06f5f2a":{
      "scriptId":"u35"},
    "c966810aeb7d4cb2ace87469980954b6":{
      "scriptId":"u36"},
    "58a3aeb92cd44813b6788929a429fd21":{
      "scriptId":"u37"},
    "c219f5cd19a84563b52112867025a2a4":{
      "scriptId":"u38"},
    "500f102c246e4f7f99a351f6a34e405b":{
      "scriptId":"u39"},
    "43cbf13cf0c14997ab1d5f5aa1d21c5c":{
      "scriptId":"u40"},
    "49fb91a94b8a4d728fe20b8c49bf7bd9":{
      "scriptId":"u41"},
    "ddbbe50cb3a743459a9b8892949c6b5b":{
      "scriptId":"u42"},
    "0e1362c342ec4d37ba07e5eaae76937c":{
      "scriptId":"u43"},
    "ed4fff34955d41e7a37d28f1e57e329e":{
      "scriptId":"u44"},
    "bbc192c3d31348789677ceffabaf0553":{
      "scriptId":"u45"},
    "fc1300964f864514b202a760116ee7ae":{
      "scriptId":"u46"},
    "451d90c7945840a7873cd4cf80d35da1":{
      "scriptId":"u47"},
    "7cc99b1136564538a3986e9a5deffc51":{
      "scriptId":"u48"},
    "9779854c81c141e0a77dcfdf31feac65":{
      "scriptId":"u49"},
    "9c28353fe38d4b51b1786a280110e250":{
      "scriptId":"u50"},
    "7032b60122754ceea43aeea1ef6efbd2":{
      "scriptId":"u51"},
    "96ca3ba9e45c4b768c314f1a740dd3d5":{
      "scriptId":"u52"}}});