$axure.loadCurrentPage({
  "url":"taskpublish.html",
  "generationDate":new Date(1527843570747.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"28950cb53c5c48b9be147d0ca2cbe5ba",
    "type":"Axure:Page",
    "name":"taskPublish",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e9fe51cdb3df4ca5b117bf407cd4b16f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":93},
            "size":{
              "width":910,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91378180560418b98d647166abc0f06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":93},
                "size":{
                  "width":910,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/showgrade/u0.png"}},
{
          "id":"4b7400fa7077407aa09876d464861499",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":153},
            "size":{
              "width":889,
              "height":409}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9ad6a0eeae4a17829bc8fa33edcded",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":121,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"964c1b54dfd8456ea4c808b11d761741",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":121,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u3.png"}},
{
              "id":"8e9497bd4a4f44b79845db08cc35c6f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"493ec93b38504579af59ae7d4504ccbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u21.png"}},
{
              "id":"15d3f7deafe04731bf9b0ea1a06f5f2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":121,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c966810aeb7d4cb2ace87469980954b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":69},
                    "size":{
                      "width":121,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u39.png"}},
{
              "id":"44fa23eb6fb5449ab89612864569be7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":0},
                "size":{
                  "width":84,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d319edd85ef24fcdb4a554bee7b24fc7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":0},
                    "size":{
                      "width":84,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u5.png"}},
{
              "id":"f16607156483482383dd923c968ff5cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":39},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf2f58ddf8bd4949919ac7c2a33c11dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":39},
                    "size":{
                      "width":84,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u23.png"}},
{
              "id":"58a3aeb92cd44813b6788929a429fd21",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":121,
                  "y":69},
                "size":{
                  "width":84,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c219f5cd19a84563b52112867025a2a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":121,
                      "y":69},
                    "size":{
                      "width":84,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u41.png"}},
{
              "id":"6ba323ac99e04da887c3c3c8c1011a0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":205,
                  "y":0},
                "size":{
                  "width":58,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f8d0dad5d0b40179283ef733c716854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":205,
                      "y":0},
                    "size":{
                      "width":58,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u7.png"}},
{
              "id":"45884f5d84594ffaa346eed3f82cecc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":205,
                  "y":39},
                "size":{
                  "width":58,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21ee639586074ec3a7ca6b3294b8caac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":205,
                      "y":39},
                    "size":{
                      "width":58,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u5.png"}},
{
              "id":"500f102c246e4f7f99a351f6a34e405b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":205,
                  "y":69},
                "size":{
                  "width":58,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43cbf13cf0c14997ab1d5f5aa1d21c5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":205,
                      "y":69},
                    "size":{
                      "width":58,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stugrademanage/u53.png"}},
{
              "id":"15e63fd45f9247b4b730165804cff078",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":263,
                  "y":0},
                "size":{
                  "width":97,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bb90dabafc4429cac5438e2e3897a83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":263,
                      "y":0},
                    "size":{
                      "width":97,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u9.png"}},
{
              "id":"23690951724f41a18de9366b6f0becb1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":263,
                  "y":39},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fde4eaebb1d846a9969ec565fd846d32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":263,
                      "y":39},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u27.png"}},
{
              "id":"49fb91a94b8a4d728fe20b8c49bf7bd9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":263,
                  "y":69},
                "size":{
                  "width":97,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ddbbe50cb3a743459a9b8892949c6b5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":263,
                      "y":69},
                    "size":{
                      "width":97,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u45.png"}},
{
              "id":"7c0d346a8a644511ab1dde8d225a267e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":0},
                "size":{
                  "width":71,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c05e33bf352f4dc8841a8dbe6d74c9ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u11.png"}},
{
              "id":"f44ba93545b2403993ba7d4b4ac5e1b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":39},
                "size":{
                  "width":71,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0474518804074d1a919e5cba23aa4475",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":39},
                    "size":{
                      "width":71,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u29.png"}},
{
              "id":"0e1362c342ec4d37ba07e5eaae76937c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":69},
                "size":{
                  "width":71,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed4fff34955d41e7a37d28f1e57e329e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":69},
                    "size":{
                      "width":71,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u47.png"}},
{
              "id":"5588762480b541c0ab9b48d957a47c06",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":431,
                  "y":0},
                "size":{
                  "width":89,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"859eaa2716814226a3b1aa83adbdf9cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":431,
                      "y":0},
                    "size":{
                      "width":89,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u13.png"}},
{
              "id":"6bd302f763c94c74b25350d54d435d2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":431,
                  "y":39},
                "size":{
                  "width":89,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30251ec8d3d9407ba95042cbbe090d87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":431,
                      "y":39},
                    "size":{
                      "width":89,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u31.png"}},
{
              "id":"bbc192c3d31348789677ceffabaf0553",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":431,
                  "y":69},
                "size":{
                  "width":89,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc1300964f864514b202a760116ee7ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":431,
                      "y":69},
                    "size":{
                      "width":89,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u49.png"}},
{
              "id":"c8afcba63c0940a294ce14aab52a350f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":165,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"65318c52cf0f4c91a36f9dd7334f806a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":165,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u15.png"}},
{
              "id":"af85ecf7eb7e4202972777fe0a213a82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":39},
                "size":{
                  "width":165,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7273ff5ceee046bca6821e29645b44b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":39},
                    "size":{
                      "width":165,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u33.png"}},
{
              "id":"451d90c7945840a7873cd4cf80d35da1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":69},
                "size":{
                  "width":165,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cc99b1136564538a3986e9a5deffc51",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":69},
                    "size":{
                      "width":165,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u51.png"}},
{
              "id":"743ad1b4409a452f98f51f66ce1550c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":685,
                  "y":0},
                "size":{
                  "width":128,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"020b7d5a693047c4bf84b60728edda05",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":685,
                      "y":0},
                    "size":{
                      "width":128,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u17.png"}},
{
              "id":"8fca95cbfacb471381c7dad2141766fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":685,
                  "y":39},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9629f39492014dc69589ec88d93c90ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":685,
                      "y":39},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u35.png"}},
{
              "id":"9779854c81c141e0a77dcfdf31feac65",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":685,
                  "y":69},
                "size":{
                  "width":128,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c28353fe38d4b51b1786a280110e250",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":685,
                      "y":69},
                    "size":{
                      "width":128,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u53.png"}},
{
              "id":"b510a3a517f74bf483d4f5fb7bab945a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":813,
                  "y":0},
                "size":{
                  "width":76,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0836e259f0d1492c9c6548eb38fbcfcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":813,
                      "y":0},
                    "size":{
                      "width":76,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u19.png"}},
{
              "id":"2a907fa855804a1f8beb4e457cddf353",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":813,
                  "y":39},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c0607c226b843aab7dcf92ffbd11941",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":813,
                      "y":39},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u37.png"}},
{
              "id":"e8ce9023d41d4cc0a52a61ca49252227",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":813,
                  "y":69},
                "size":{
                  "width":76,
                  "height":340}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d9e794c7e06401086ee16df26a54f67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":813,
                      "y":69},
                    "size":{
                      "width":76,
                      "height":340}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/taskpublish/u55.png"}}]},
{
          "id":"7032b60122754ceea43aeea1ef6efbd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":243},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ca3ba9e45c4b768c314f1a740dd3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":243},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7024d5b6e39a49c9b0e972c394187849",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":103},
            "size":{
              "width":889,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef569c12f2ce4198996ee74608a4664f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":103},
                "size":{
                  "width":889,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/submitregist/u47.png"}},
{
          "id":"023f2018d6194265b6fbd19653601f3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":816,
              "y":108},
            "size":{
              "width":103,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca25d621566414297309479af0329ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":816,
                  "y":108},
                "size":{
                  "width":103,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/submitregist/u49.png"}},
{
          "id":"e931f51f656244a4a335f78e3b1af488",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":744,
              "y":112},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b684a42af5f47c184bc6d8b87c68086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":744,
                  "y":112},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33a20879825641c2b6205ca3af28ab63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":877,
              "y":196},
            "size":{
              "width":49,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77331ab4c9024b9e9cf266247450ee9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":877,
                  "y":196},
                "size":{
                  "width":49,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stugrademanage/u77.png"}},
{
          "id":"1e73518d7f914af48b7b086020f03773",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":902,
              "y":216}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f5a43c30504066b0173c98aab3dd6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":902,
                  "y":216}},
              "adaptiveStyles":{
}}]},
{
          "id":"03a782ffaa924fc3ae81704cd088b171",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":313},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10ee6a27d4cc48b5bc6c890fa3c167fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":313},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"095b827f04ef463faeaaa54f849402ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":20},
            "size":{
              "width":180,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4aa407bfcbc4138a1c2478d11321356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":20},
                "size":{
                  "width":180,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/taskpublish/u71.png"}},
{
          "id":"5352bfeb8fbe44c5a76a32f4ef79e01b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21310e495324df0986bc0f00e19ca4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":110}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "e9fe51cdb3df4ca5b117bf407cd4b16f":{
      "scriptId":"u0"},
    "a91378180560418b98d647166abc0f06":{
      "scriptId":"u1"},
    "4b7400fa7077407aa09876d464861499":{
      "scriptId":"u2"},
    "eb9ad6a0eeae4a17829bc8fa33edcded":{
      "scriptId":"u3"},
    "964c1b54dfd8456ea4c808b11d761741":{
      "scriptId":"u4"},
    "44fa23eb6fb5449ab89612864569be7c":{
      "scriptId":"u5"},
    "d319edd85ef24fcdb4a554bee7b24fc7":{
      "scriptId":"u6"},
    "6ba323ac99e04da887c3c3c8c1011a0d":{
      "scriptId":"u7"},
    "9f8d0dad5d0b40179283ef733c716854":{
      "scriptId":"u8"},
    "15e63fd45f9247b4b730165804cff078":{
      "scriptId":"u9"},
    "8bb90dabafc4429cac5438e2e3897a83":{
      "scriptId":"u10"},
    "7c0d346a8a644511ab1dde8d225a267e":{
      "scriptId":"u11"},
    "c05e33bf352f4dc8841a8dbe6d74c9ae":{
      "scriptId":"u12"},
    "5588762480b541c0ab9b48d957a47c06":{
      "scriptId":"u13"},
    "859eaa2716814226a3b1aa83adbdf9cc":{
      "scriptId":"u14"},
    "c8afcba63c0940a294ce14aab52a350f":{
      "scriptId":"u15"},
    "65318c52cf0f4c91a36f9dd7334f806a":{
      "scriptId":"u16"},
    "743ad1b4409a452f98f51f66ce1550c7":{
      "scriptId":"u17"},
    "020b7d5a693047c4bf84b60728edda05":{
      "scriptId":"u18"},
    "b510a3a517f74bf483d4f5fb7bab945a":{
      "scriptId":"u19"},
    "0836e259f0d1492c9c6548eb38fbcfcf":{
      "scriptId":"u20"},
    "8e9497bd4a4f44b79845db08cc35c6f6":{
      "scriptId":"u21"},
    "493ec93b38504579af59ae7d4504ccbb":{
      "scriptId":"u22"},
    "f16607156483482383dd923c968ff5cf":{
      "scriptId":"u23"},
    "cf2f58ddf8bd4949919ac7c2a33c11dd":{
      "scriptId":"u24"},
    "45884f5d84594ffaa346eed3f82cecc7":{
      "scriptId":"u25"},
    "21ee639586074ec3a7ca6b3294b8caac":{
      "scriptId":"u26"},
    "23690951724f41a18de9366b6f0becb1":{
      "scriptId":"u27"},
    "fde4eaebb1d846a9969ec565fd846d32":{
      "scriptId":"u28"},
    "f44ba93545b2403993ba7d4b4ac5e1b7":{
      "scriptId":"u29"},
    "0474518804074d1a919e5cba23aa4475":{
      "scriptId":"u30"},
    "6bd302f763c94c74b25350d54d435d2c":{
      "scriptId":"u31"},
    "30251ec8d3d9407ba95042cbbe090d87":{
      "scriptId":"u32"},
    "af85ecf7eb7e4202972777fe0a213a82":{
      "scriptId":"u33"},
    "7273ff5ceee046bca6821e29645b44b7":{
      "scriptId":"u34"},
    "8fca95cbfacb471381c7dad2141766fe":{
      "scriptId":"u35"},
    "9629f39492014dc69589ec88d93c90ea":{
      "scriptId":"u36"},
    "2a907fa855804a1f8beb4e457cddf353":{
      "scriptId":"u37"},
    "5c0607c226b843aab7dcf92ffbd11941":{
      "scriptId":"u38"},
    "15d3f7deafe04731bf9b0ea1a06f5f2a":{
      "scriptId":"u39"},
    "c966810aeb7d4cb2ace87469980954b6":{
      "scriptId":"u40"},
    "58a3aeb92cd44813b6788929a429fd21":{
      "scriptId":"u41"},
    "c219f5cd19a84563b52112867025a2a4":{
      "scriptId":"u42"},
    "500f102c246e4f7f99a351f6a34e405b":{
      "scriptId":"u43"},
    "43cbf13cf0c14997ab1d5f5aa1d21c5c":{
      "scriptId":"u44"},
    "49fb91a94b8a4d728fe20b8c49bf7bd9":{
      "scriptId":"u45"},
    "ddbbe50cb3a743459a9b8892949c6b5b":{
      "scriptId":"u46"},
    "0e1362c342ec4d37ba07e5eaae76937c":{
      "scriptId":"u47"},
    "ed4fff34955d41e7a37d28f1e57e329e":{
      "scriptId":"u48"},
    "bbc192c3d31348789677ceffabaf0553":{
      "scriptId":"u49"},
    "fc1300964f864514b202a760116ee7ae":{
      "scriptId":"u50"},
    "451d90c7945840a7873cd4cf80d35da1":{
      "scriptId":"u51"},
    "7cc99b1136564538a3986e9a5deffc51":{
      "scriptId":"u52"},
    "9779854c81c141e0a77dcfdf31feac65":{
      "scriptId":"u53"},
    "9c28353fe38d4b51b1786a280110e250":{
      "scriptId":"u54"},
    "e8ce9023d41d4cc0a52a61ca49252227":{
      "scriptId":"u55"},
    "7d9e794c7e06401086ee16df26a54f67":{
      "scriptId":"u56"},
    "7032b60122754ceea43aeea1ef6efbd2":{
      "scriptId":"u57"},
    "96ca3ba9e45c4b768c314f1a740dd3d5":{
      "scriptId":"u58"},
    "7024d5b6e39a49c9b0e972c394187849":{
      "scriptId":"u59"},
    "ef569c12f2ce4198996ee74608a4664f":{
      "scriptId":"u60"},
    "023f2018d6194265b6fbd19653601f3c":{
      "scriptId":"u61"},
    "cca25d621566414297309479af0329ed":{
      "scriptId":"u62"},
    "e931f51f656244a4a335f78e3b1af488":{
      "scriptId":"u63"},
    "4b684a42af5f47c184bc6d8b87c68086":{
      "scriptId":"u64"},
    "33a20879825641c2b6205ca3af28ab63":{
      "scriptId":"u65"},
    "77331ab4c9024b9e9cf266247450ee9b":{
      "scriptId":"u66"},
    "1e73518d7f914af48b7b086020f03773":{
      "scriptId":"u67"},
    "50f5a43c30504066b0173c98aab3dd6e":{
      "scriptId":"u68"},
    "03a782ffaa924fc3ae81704cd088b171":{
      "scriptId":"u69"},
    "10ee6a27d4cc48b5bc6c890fa3c167fa":{
      "scriptId":"u70"},
    "095b827f04ef463faeaaa54f849402ed":{
      "scriptId":"u71"},
    "a4aa407bfcbc4138a1c2478d11321356":{
      "scriptId":"u72"},
    "5352bfeb8fbe44c5a76a32f4ef79e01b":{
      "scriptId":"u73"},
    "a21310e495324df0986bc0f00e19ca4b":{
      "scriptId":"u74"}}});